# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a459da06c23f6cd97a6a67dfcffdc249195ee69b1c24fd7bd830c1452ce2bee87b902c676879f9d57434f3281066120c25b940482f5b29d754d01d027239803d

test:
  secret_key_base: da61152bdf96bc24b0051a5f199b29559960af01d832fa47d02aeb332438146f0b20f4429dd803d450f10469ae4c56ceed769d6dc76a5f611d3a2027327c1ce9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
